export default {
    showInStockOnly: true,
    products: [
        {
            productId: "1955287",
            type: "product",
            title: "Bosch Serie 2 SMV40C30GB Fully Integrated Dishwasher",
            htmlTitle: "",
            code: "88701207",
            averageRating: 4.2,
            reviews: 304,
            price: { was: "", then1: "", then2: "", now: "397.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/234378764?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "234378764",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "Silver",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/234378764?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/234378764?",
                    isAvailable: true,
                    skuId: "234378764",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Bosch",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                cutlerybasket: "Basket",
                integratedorfreestanding: "Integrated",
                quietmark: "NO",
                slimdepth: "NO",
                placesettings: "12",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "4215447",
            type: "product",
            title: "Bosch Serie 4 SMV46JX01G Fully Integrated Dishwasher",
            htmlTitle: "",
            code: "88701206",
            averageRating: 4.4,
            reviews: 61,
            price: { was: "", then1: "", then2: "", now: "479.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/238078364?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "238078364",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "Metallics",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/238078364?cropN=0.40421052631578946,0.5873684210526315,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/238078364?",
                    isAvailable: true,
                    skuId: "238078364",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Bosch",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                cutlerybasket: "Basket",
                amperage: "10A",
                integratedorfreestanding: "Integrated",
                weight: "33.23kg",
                quietmark: "NO",
                slimdepth: "NO",
                placesettings: "13",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "4189551",
            type: "product",
            title: "Siemens iQ300 SN236W03MG Freestanding Dishwasher, White",
            htmlTitle: "",
            code: "81701602",
            averageRating: 4.7,
            reviews: 19,
            price: { was: "", then1: "", then2: "", now: "549.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/238008972?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "238008972",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "White",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/238008972?cropN=0.4054621848739496,0.5840336134453782,0.19117647058823528,0.19117647058823528&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/238008972?",
                    isAvailable: true,
                    skuId: "238008972",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Siemens",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                cutlerybasket: "Tray",
                amperage: "10A",
                integratedorfreestanding: "Freestanding",
                weight: "50.1kg",
                quietmark: "NO",
                slimdepth: "NO",
                placesettings: "14",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "3224775",
            type: "product",
            title: "Neff N50 S513G60X0G Fully Integrated Dishwasher",
            htmlTitle: "",
            code: "88701304",
            averageRating: 4.3,
            reviews: 76,
            price: { was: "", then1: "", then2: "", now: "459.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/236888510?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "236888510",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "White",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/236888510?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/236888510?",
                    isAvailable: true,
                    skuId: "236888510",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Neff",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                cutlerybasket: "Basket",
                integratedorfreestanding: "Integrated",
                quietmark: "NO",
                slimdepth: "NO",
                placesettings: "12",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "3329013",
            type: "product",
            title: "John Lewis & Partners JLDWW1327 Freestanding Dishwasher, White",
            htmlTitle: "",
            code: "81700206",
            averageRating: 4.2,
            reviews: 155,
            price: { was: "", then1: "", then2: "", now: "349.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/237045290alt1?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "237045290",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "White",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/237045290?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/237045290alt1?",
                    isAvailable: true,
                    skuId: "237045290",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "John Lewis & Partners",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                cutlerybasket: "Basket",
                integratedorfreestanding: "Freestanding",
                quietmark: "NO",
                slimdepth: "NO",
                placesettings: "13",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "3244905",
            type: "product",
            title: "Neff N50 S513K60X0G Fully Integrated Dishwasher",
            htmlTitle: "",
            code: "88701308",
            averageRating: 4.2,
            reviews: 147,
            price: { was: "", then1: "", then2: "", now: "499.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/236931072?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "236931072",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "White",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/236931072?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/236931072?",
                    isAvailable: true,
                    skuId: "236931072",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: true,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Neff",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                cutlerybasket: "Tray",
                integratedorfreestanding: "Integrated",
                quietmark: "NO",
                slimdepth: "NO",
                placesettings: "13",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "4131668",
            type: "product",
            title: "Bosch Serie 4 SMS46MW03G Freestanding Dishwasher, White",
            htmlTitle: "",
            code: "81701204",
            averageRating: 4.7,
            reviews: 28,
            price: { was: "", then1: "", then2: "", now: "529.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/238008964?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "238008964",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "White",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/238008964?cropN=0.38105263157894737,0.6547368421052632,0.07368421052631578,0.07368421052631578&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/238008964?",
                    isAvailable: true,
                    skuId: "238008964",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Bosch",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                cutlerybasket: "Tray",
                amperage: "10A",
                integratedorfreestanding: "Freestanding",
                weight: "45.66kg",
                quietmark: "Not Accredited",
                slimdepth: "NO",
                placesettings: "14",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "4191473",
            type: "product",
            title: "Siemens iQ300 SN236I02MG Freestanding Dishwasher, Grey",
            htmlTitle: "",
            code: "81701605",
            averageRating: 4.8,
            reviews: 31,
            price: { was: "", then1: "", then2: "", now: "599.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/238008985?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "238008985",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "Silver",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/238008985?cropN=0.4,0.6021052631578947,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/238008985?",
                    isAvailable: true,
                    skuId: "238008985",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Siemens",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                cutlerybasket: "Tray",
                amperage: "10A",
                integratedorfreestanding: "Freestanding",
                weight: "50kg",
                quietmark: "NO",
                slimdepth: "NO",
                placesettings: "14",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "3747214",
            type: "product",
            title: "Samsung Series 6 DW60M6050FS Freestanding Dishwasher, Silver",
            htmlTitle: "",
            code: "81705403",
            averageRating: 2.3,
            reviews: 9,
            price: { was: "", then1: "", then2: "", now: "459.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/237723440?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "237723440",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "Silver",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/237723440?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/237723440?",
                    isAvailable: true,
                    skuId: "237723440",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Samsung",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                augmentedrealityimageavailable: "YES",
                dishwashersize: "Full",
                cutlerybasket: "Tray",
                integratedorfreestanding: "Freestanding",
                weight: "50kg",
                quietmark: "YES",
                slimdepth: "NO",
                placesettings: "14",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "3328837",
            type: "product",
            title: "John Lewis & Partners JLDWS1328 Freestanding Dishwasher, Stainless Steel",
            htmlTitle: "",
            code: "81700207",
            averageRating: 3.5,
            reviews: 60,
            price: { was: "", then1: "", then2: "", now: "379.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/237059569alt1?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "237059569",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "Silver",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/237059569?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/237059569alt1?",
                    isAvailable: true,
                    skuId: "237059569",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "John Lewis & Partners",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                cutlerybasket: "Basket",
                integratedorfreestanding: "Freestanding",
                quietmark: "NO",
                slimdepth: "NO",
                placesettings: "13",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "4815251",
            type: "product",
            title: "Bosch Serie 4 SMS46II01G Freestanding Dishwasher, Stainless Steel",
            htmlTitle: "",
            code: "81701205",
            averageRating: 4.8,
            reviews: 5,
            price: { was: "", then1: "", then2: "", now: "519.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/238008966?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "238008966",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "Grey",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/238008966?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/238008966?",
                    isAvailable: true,
                    skuId: "238008966",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Bosch",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                cutlerybasket: "Basket",
                amperage: "10A",
                integratedorfreestanding: "Freestanding",
                weight: "45.6kg",
                quietmark: "NO",
                slimdepth: "NO",
                placesettings: "13",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "3215505",
            type: "product",
            title: "Bosch Serie 6 SMS67MW00G Freestanding Dishwasher, White",
            htmlTitle: "",
            code: "81701108",
            averageRating: 4.6,
            reviews: 161,
            price: { was: "", then1: "", then2: "", now: "629.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/236888508?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "236888508",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "White",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/236888508?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/236888508?",
                    isAvailable: true,
                    skuId: "236888508",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: true,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Bosch",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                cutlerybasket: "Tray",
                integratedorfreestanding: "Freestanding",
                quietmark: "NO",
                slimdepth: "NO",
                placesettings: "14",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "4205800",
            type: "product",
            title: "John Lewis & Partners JLBIDW1319 Fully Integrated Dishwasher",
            htmlTitle: "",
            code: "88700202",
            averageRating: 3.7,
            reviews: 32,
            price: { was: "", then1: "", then2: "", now: "429.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/238095972alt1?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "238095972",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "Silver",
                    colorSwatchUrl: "//johnlewis.scene7.com/is/image/JohnLewis/1?cropN=1,1,1,1&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/238095972alt1?",
                    isAvailable: true,
                    skuId: "238095972",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "John Lewis & Partners",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                range: "Dishwasher",
                dishwashersize: "Full",
                cutlerybasket: "Basket",
                integratedorfreestanding: "Integrated",
                weight: "37.08kg",
                slimdepth: "NO",
                placesettings: "13",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "4983308",
            type: "product",
            title: "Samsung Series 6 DW60M6050FW Freestanding Dishwasher, White",
            htmlTitle: "",
            code: "81705404",
            averageRating: 2.0,
            reviews: 2,
            price: { was: "", then1: "", then2: "", now: "426.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/237723441?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "237723441",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "White",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/237723441?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/237723441?",
                    isAvailable: true,
                    skuId: "237723441",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Samsung",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                augmentedrealityimageavailable: "YES",
                dishwashersize: "Full",
                cutlerybasket: "Tray",
                integratedorfreestanding: "Freestanding",
                weight: "50kg",
                slimdepth: "NO",
                placesettings: "14",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "4125616",
            type: "product",
            title: "Miele G7360 SCVi Integrated Dishwasher",
            htmlTitle: "",
            code: "88703001",
            averageRating: 5.0,
            reviews: 1,
            price: { was: "", then1: "", then2: "", now: "1540.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/238032191?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "238032191",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "Silver",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/238032191alt2?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/238032191?",
                    isAvailable: true,
                    skuId: "238032191",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Miele",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                cutlerybasket: "Tray",
                amperage: "10A",
                integratedorfreestanding: "Integrated",
                weight: "48kg",
                onlineexclusive: "Information not available",
                quietmark: "YES",
                slimdepth: "NO",
                placesettings: "14",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "4233088",
            type: "product",
            title: "John Lewis & Partners JLBIDW1419 Fully Integrated Dishwasher",
            htmlTitle: "",
            code: "88700203",
            averageRating: 3.4,
            reviews: 28,
            price: { was: "", then1: "", then2: "", now: "429.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/238096018alt1?",
            displaySpecialOffer: "Save £60 (price includes saving)",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {
                    customSpecialOfferId: "",
                    imageURL: "",
                    linkText: "",
                    linkURL: "",
                    longDescription: "Save £60 (price includes saving)",
                    promoImageName: "",
                    siteDisplayName: "Save £60 (price includes saving)",
                },
            },
            nonPromoMessage: "",
            defaultSkuId: "238096018",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "White",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/238096018?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/238096018alt1?",
                    isAvailable: true,
                    skuId: "238096018",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "John Lewis & Partners",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                integratedorfreestanding: "Integrated",
                weight: "37kg",
                slimdepth: "NO",
                placesettings: "14",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: true,
                simpleAddToBasket: false,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "5078149",
            type: "product",
            title: "Miele G5223SC Freestanding Dishwasher, White",
            htmlTitle: "",
            code: "81702906",
            averageRating: 0.0,
            reviews: 0,
            price: { was: "", then1: "", then2: "", now: "749.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/238750556?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "238750556",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "White",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/238750556?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/238750556?",
                    isAvailable: true,
                    skuId: "238750556",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Miele",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                autodose: "NO",
                dishwashersize: "Full",
                integratedorfreestanding: "Freestanding",
                widthbuiltinovens: "59.8cm",
                weight: "43.7kg",
                cutlerybasket: "Tray",
                amperage: "10A",
                onlineexclusive: "Information not available",
                quietmark: "NO",
                slimdepth: "NO",
                placesettings: "14",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "5419780",
            type: "product",
            title: "John Lewis & Partners JLBIDW918 Integrated Slimline Dishwasher",
            htmlTitle: "",
            code: "88710201",
            averageRating: 0.0,
            reviews: 0,
            price: { was: "", then1: "", then2: "", now: "389.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/238893445?",
            displaySpecialOffer: "Save £40 (price includes saving)",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {
                    customSpecialOfferId: "",
                    imageURL: "",
                    linkText: "",
                    linkURL: "",
                    longDescription: "Save £40 (price includes saving)",
                    promoImageName: "",
                    siteDisplayName: "Save £40 (price includes saving)",
                },
            },
            nonPromoMessage: "",
            defaultSkuId: "238893445",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "Black",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/238893445?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/238893445?",
                    isAvailable: true,
                    skuId: "238893445",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "John Lewis & Partners",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                autodose: "NO",
                dishwashersize: "Slimline",
                cutlerybasket: "Basket",
                amperage: "10A",
                integratedorfreestanding: "Freestanding",
                weight: "37.13kg",
                onlineexclusive: "Information not available",
                quietmark: "Not Accredited",
                slimdepth: "YES",
                placesettings: "9",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: true,
                simpleAddToBasket: false,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "5492087",
            type: "product",
            title: "Hotpoint HFC 3C26 W C UK Freestanding Dishwasher, White",
            htmlTitle: "",
            code: "81702201",
            averageRating: 0.0,
            reviews: 0,
            price: { was: "", then1: "", then2: "", now: "309.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/238970597?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "238970597",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "White",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/238970597?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/238970597?",
                    isAvailable: true,
                    skuId: "238970597",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Hotpoint",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                autodose: "NO",
                dishwashersize: "Full",
                integratedorfreestanding: "Freestanding",
                widthbuiltinovens: "60cm",
                weight: "47kg",
                cutlerybasket: "Basket",
                amperage: "13A",
                onlineexclusive: "Information not available",
                quietmark: "NO",
                slimdepth: "NO",
                placesettings: "14",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "4185382",
            type: "product",
            title: "AEG FSS62807P Fully Integrated Dishwasher",
            htmlTitle: "",
            code: "88700506",
            averageRating: 3.6,
            reviews: 17,
            price: { was: "", then1: "", then2: "", now: "729.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/238097161?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "238097161",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "White",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/238097161?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/238097161?",
                    isAvailable: true,
                    skuId: "238097161",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "AEG",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                cutlerybasket: "Tray",
                integratedorfreestanding: "Integrated",
                weight: "38.67kg",
                slimdepth: "NO",
                placesettings: "13",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "4323086",
            type: "product",
            title: "AEG FFE63806PM Freestanding Dishwasher, Silver",
            htmlTitle: "",
            code: "81700505",
            averageRating: 3.5,
            reviews: 2,
            price: { was: "", then1: "", then2: "", now: "949.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/238280342?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "238280342",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "Silver",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/238280342?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/238280342?",
                    isAvailable: true,
                    skuId: "238280342",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "AEG",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                autodose: "NO",
                dishwashersize: "Full",
                cutlerybasket: "Basket",
                amperage: "10A",
                integratedorfreestanding: "Freestanding",
                widthbuiltinovens: "59.6cm",
                weight: "50.2kg",
                quietmark: "YES",
                slimdepth: "NO",
                placesettings: "13",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "3832171",
            type: "product",
            title: "AEG FFE63806PW Freestanding Dishwasher, White",
            htmlTitle: "",
            code: "81700601",
            averageRating: 4.4,
            reviews: 5,
            price: { was: "", then1: "", then2: "", now: "949.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/237584692?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "237584692",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "White",
                    colorSwatchUrl: "//johnlewis.scene7.com/is/image/JohnLewis/pswatch_white?cropN=0,0,0.0,0.0&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/237584692?",
                    isAvailable: true,
                    skuId: "237584692",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "AEG",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                integratedorfreestanding: "Freestanding",
                widthbuiltinovens: "60cm",
                weight: "46kg",
                cutlerybasket: "Basket",
                amperage: "10A",
                onlineexclusive: "Information not available",
                quietmark: "YES",
                slimdepth: "NO",
                placesettings: "13",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "3358186",
            type: "product",
            title: "Samsung Series 6 DW60M6040BB Fully Integrated Dishwasher",
            htmlTitle: "",
            code: "88700905",
            averageRating: 1.0,
            reviews: 3,
            price: { was: "", then1: "", then2: "", now: "419.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/237196750?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "237196750",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "Silver",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/237196750?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/237196750?",
                    isAvailable: true,
                    skuId: "237196750",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "Samsung",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                augmentedrealityimageavailable: "YES",
                dishwashersize: "Full",
                cutlerybasket: "Basket",
                integratedorfreestanding: "Integrated",
                weight: "43kg",
                slimdepth: "NO",
                placesettings: "13",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
        {
            productId: "3352471",
            type: "product",
            title: "AEG FFE63700PM Freestanding Dishwasher, Stainless Steel",
            htmlTitle: "",
            code: "81700511",
            averageRating: 4.3,
            reviews: 9,
            price: { was: "", then1: "", then2: "", now: "719.00", uom: "", currency: "GBP" },
            image: "//johnlewis.scene7.com/is/image/JohnLewis/237203804?",
            displaySpecialOffer: "",
            promoMessages: {
                reducedToClear: false,
                priceMatched: "",
                offer: "",
                customPromotionalMessage: "",
                bundleHeadline: "",
                customSpecialOffer: {},
            },
            nonPromoMessage: "",
            defaultSkuId: "237203804",
            colorSwatches: [
                {
                    color: "",
                    basicColor: "Silver",
                    colorSwatchUrl:
                        "//johnlewis.scene7.com/is/image/JohnLewis/237203804?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
                    imageUrl: "//johnlewis.scene7.com/is/image/JohnLewis/237203804?",
                    isAvailable: true,
                    skuId: "237203804",
                },
            ],
            colorSwatchSelected: 0,
            colorWheelMessage: "",
            outOfStock: false,
            emailMeWhenAvailable: false,
            availabilityMessage: "",
            compare: true,
            fabric: "",
            swatchAvailable: false,
            categoryQuickViewEnabled: false,
            swatchCategoryType: "",
            brand: "AEG",
            ageRestriction: 0,
            isInStoreOnly: false,
            isMadeToMeasure: false,
            isBundle: false,
            isProductSet: false,
            promotionalFeatures: [],
            features: [],
            dynamicAttributes: {
                dishwashersize: "Full",
                cutlerybasket: "Basket",
                integratedorfreestanding: "Freestanding",
                quietmark: "YES",
                slimdepth: "NO",
                placesettings: "15",
            },
            directorate: "Technology Directora",
            futureRelease: false,
            multiSku: false,
            fabricByLength: false,
            quickAddToBasket: {
                showPermanentOos: false,
                showMoreInfoRedirectPDP: false,
                simpleAddToBasket: true,
                simpleMobileEmailMe: false,
                showEmailMeTriggerQV: false,
                showChooseSizeTriggerQV: false,
            },
            permanentOos: false,
        },
    ],
    facets: [
        {
            dimensionName: "childSKUs.hideOutOfStock",
            name: "Stock Availability",
            type: "Single",
            tooltip: "Stock Availability",
            details: [
                {
                    facetId: "/electricals/dishwashers/show-in-stock-items-only/_/N-adoZ1z0wxdt",
                    label: "Show in stock items only",
                    qty: "43",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
        {
            dimensionName: "product.newIn",
            name: "New In",
            type: "Single",
            tooltip: "New In",
            details: [
                {
                    facetId: "/electricals/dishwashers/new-in/_/N-adoZ7lhg",
                    label: "New In",
                    qty: "5",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
        {
            dimensionName: "sku.offerType",
            name: "On Offer",
            type: "Single",
            tooltip: "On Offer",
            details: [
                {
                    facetId: "/electricals/dishwashers/all-offers/_/N-adoZ1yzvw1q",
                    label: "All Offers",
                    qty: "3",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
        {
            dimensionName: "brand",
            name: "Brand",
            type: "Single",
            tooltip: "Brand",
            details: [
                {
                    facetId: "/electricals/dishwashers/aeg/_/N-adoZ1z13xop",
                    label: "AEG",
                    qty: "8",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/beko/_/N-adoZ1z0qjig",
                    label: "Beko",
                    qty: "2",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/bosch/_/N-adoZ1z13z3z",
                    label: "Bosch",
                    qty: "23",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/fisher-paykel/_/N-adoZ1z13xoo",
                    label: "Fisher & Paykel",
                    qty: "5",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/hotpoint/_/N-adoZ1z13yrm",
                    label: "Hotpoint",
                    qty: "2",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/indesit/_/N-adoZ1z13y6q",
                    label: "Indesit",
                    qty: "2",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/john-lewis-partners/_/N-adoZ1yzsz8d",
                    label: "John Lewis & Partners",
                    qty: "7",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/miele/_/N-adoZ1z1411z",
                    label: "Miele",
                    qty: "5",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/neff/_/N-adoZ1z13ypo",
                    label: "Neff",
                    qty: "6",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/samsung/_/N-adoZ1z13z13",
                    label: "Samsung",
                    qty: "7",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/siemens/_/N-adoZ1z13zg7",
                    label: "Siemens",
                    qty: "3",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/zanussi/_/N-adoZ1z13yzi",
                    label: "Zanussi",
                    qty: "5",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
        {
            dimensionName: "price",
            name: "Price",
            type: "Single",
            tooltip: "Price",
            details: [
                {
                    facetId:
                        "/electricals/dishwashers/price=220-370/_/N-ado?price=220-370&priceBands=220-370,370-420,420-520,520-700,710-1550",
                    label: "£220 - £370",
                    qty: "12",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId:
                        "/electricals/dishwashers/price=370-420/_/N-ado?price=370-420&priceBands=220-370,370-420,420-520,520-700,710-1550",
                    label: "£370 - £420",
                    qty: "13",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId:
                        "/electricals/dishwashers/price=420-520/_/N-ado?price=420-520&priceBands=220-370,370-420,420-520,520-700,710-1550",
                    label: "£420 - £520",
                    qty: "16",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId:
                        "/electricals/dishwashers/price=520-700/_/N-ado?price=520-700&priceBands=220-370,370-420,420-520,520-700,710-1550",
                    label: "£520 - £700",
                    qty: "17",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId:
                        "/electricals/dishwashers/price=710-1550/_/N-ado?price=710-1550&priceBands=220-370,370-420,420-520,520-700,710-1550",
                    label: "£710 - £1550",
                    qty: "17",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
        {
            dimensionName: "features.displayName",
            name: "Features",
            type: "Single",
            tooltip: "Features",
            details: [
                {
                    facetId: "/electricals/dishwashers/quick-wash/_/N-adoZ1z13j1z",
                    label: "Quick Wash",
                    qty: "75",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/digital-display/_/N-adoZ1z13j08",
                    label: "Digital Display",
                    qty: "66",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/timer-delay/_/N-adoZ1z13j20",
                    label: "Timer Delay",
                    qty: "64",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/time-remaining-indicator/_/N-adoZ1z13j21",
                    label: "Time Remaining Indicator",
                    qty: "58",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/child-lock/_/N-adoZ1z13fxf",
                    label: "Child Lock",
                    qty: "37",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/quiet-mark/_/N-adoZ1z13jb3",
                    label: "Quiet Mark",
                    qty: "16",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/slimline/_/N-adoZ1z0cpi1",
                    label: "Slimline",
                    qty: "12",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/smart/_/N-adoZ1z0h07w",
                    label: "Smart",
                    qty: "10",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/glass-care/_/N-adoZ1z13j1y",
                    label: "Glass Care",
                    qty: "7",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
        {
            dimensionName: "childSKUs.basicColor",
            name: "Colour",
            type: "Single",
            tooltip: "Colour",
            details: [
                {
                    facetId: "/electricals/dishwashers/white/_/N-adoZ1z141c2",
                    label: "White",
                    qty: "44",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/silver/_/N-adoZ1z141fz",
                    label: "Silver",
                    qty: "25",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/black/_/N-adoZ1z141fu",
                    label: "Black",
                    qty: "2",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/grey/_/N-adoZ1z14178",
                    label: "Grey",
                    qty: "2",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/metallics/_/N-adoZ1z141b3",
                    label: "Metallics",
                    qty: "1",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
        {
            dimensionName: "integratedorfreestanding",
            name: "Integrated or Freestanding",
            type: "Single",
            tooltip: "Integrated or Freestanding",
            details: [
                {
                    facetId: "/electricals/dishwashers/freestanding/_/N-adoZ1z0rooj",
                    label: "Freestanding",
                    qty: "43",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/integrated/_/N-adoZ1z0rnds",
                    label: "Integrated",
                    qty: "32",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
        {
            dimensionName: "dishwashersize",
            name: "Dishwasher Size",
            type: "Single",
            tooltip: "Dishwasher Size",
            details: [
                {
                    facetId: "/electricals/dishwashers/size=full/_/N-adoZ1z0rie6",
                    label: "Full",
                    qty: "60",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/size=slimline/_/N-adoZ1z0rni3",
                    label: "Slimline",
                    qty: "12",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/size=compact/_/N-adoZ1z0ri83",
                    label: "Compact",
                    qty: "3",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
        {
            dimensionName: "slimdepth",
            name: "Slim Depth",
            type: "Single",
            tooltip: "Slim Depth",
            details: [
                {
                    facetId: "/electricals/dishwashers/no/_/N-adoZ1yzx6ex",
                    label: "NO",
                    qty: "66",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/yes/_/N-adoZ1yzx6eu",
                    label: "YES",
                    qty: "6",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
        {
            dimensionName: "cutlerybasket",
            name: "Cutlery Holder",
            type: "Single",
            tooltip: "Cutlery Holder",
            details: [
                {
                    facetId: "/electricals/dishwashers/basket/_/N-adoZ1z00fr1",
                    label: "Basket",
                    qty: "44",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/tray/_/N-adoZ1z00fqs",
                    label: "Tray",
                    qty: "23",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/basket-tray/_/N-adoZ1z00fqr",
                    label: "Basket & Tray",
                    qty: "4",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
        {
            dimensionName: "quietmark",
            name: "Quiet Mark",
            type: "Single",
            tooltip: "Quiet Mark",
            details: [
                {
                    facetId: "/electricals/dishwashers/no/_/N-adoZ1yzu3i2",
                    label: "NO",
                    qty: "46",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/yes/_/N-adoZ1yzu3hz",
                    label: "YES",
                    qty: "14",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/not-accredited/_/N-adoZlsjx",
                    label: "Not Accredited",
                    qty: "2",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
        {
            dimensionName: "freeGuarantees",
            name: "Free Guarantee",
            type: "Single",
            tooltip: "Free Guarantee",
            details: [
                {
                    facetId: "/electricals/dishwashers/2-year-guarantee-included/_/N-adoZ1yzvi2y",
                    label: "2 year guarantee included",
                    qty: "64",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/3-year-guarantee-included/_/N-adoZ1yzvi32",
                    label: "3 year guarantee included",
                    qty: "6",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/5-year-guarantee-included/_/N-adoZ1yzvi2z",
                    label: "5 year guarantee included",
                    qty: "5",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
        {
            dimensionName: "childSKUs.deliveryGroup",
            name: "Delivery Options",
            type: "Single",
            tooltip: "Delivery Options",
            details: [
                {
                    facetId: "/electricals/dishwashers/next-day-delivery/_/N-adoZ1z0ktrf",
                    label: "Next Day Delivery",
                    qty: "38",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/standard-uk-delivery/_/N-adoZ1z0ktrh",
                    label: "Standard UK Delivery",
                    qty: "54",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/direct-from-our-supplier/_/N-adoZ1z0ktre",
                    label: "Direct from our supplier",
                    qty: "21",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
        {
            dimensionName: "productRating.averageRating",
            name: "Avg. Review Rating",
            type: "Single",
            tooltip: "Avg. Review Rating",
            details: [
                {
                    facetId: "/electricals/dishwashers/4+/_/N-adoZ6qpe",
                    label: "4+",
                    qty: "45",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/3-4/_/N-adoZvfj",
                    label: "3-4",
                    qty: "9",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/2-3/_/N-adoZvfi",
                    label: "2-3",
                    qty: "4",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
                {
                    facetId: "/electricals/dishwashers/1-2/_/N-adoZvfh",
                    label: "1-2",
                    qty: "2",
                    color: "",
                    colorSwatchUrl: "",
                    isSelected: "false",
                },
            ],
        },
    ],
    results: 75,
    pagesAvailable: 4,
    crumbs: [
        { clickable: "true", displayName: "Electricals", type: "CATALOGUE", item: "500001" },
        { clickable: "false", displayName: "Dishwashers", type: "CATALOGUE", item: "6000047" },
    ],
    dynamicBannerId: "electricals/dishwashers/dishwashers-130720 | dishwashers-hyb-261018",
    banners: {
        topBannerId: "electricals/dishwashers/dishwashers-130720",
        blockBannerId: "dishwashers-hyb-261018",
        seoBannerId: "20112019/ado",
    },
    categoryTitle: "Dishwashers",
    seoBannerId: "20112019/ado",
    seoInformation: {
        description:
            "Shop for Dishwashers from our Electricals range at John Lewis & Partners. Free UK mainland delivery when you spend £50 and over.",
        noIndex: false,
    },
    pageInformation: {
        title: "Dishwashers | Electricals | John Lewis & Partners",
        heading: "Dishwashers",
        description:
            "Shop for Dishwashers from our Electricals range at John Lewis & Partners. Free UK mainland delivery when you spend £50 and over.",
        noIndex: false,
        noFollow: false,
    },
    triggeredRules: { dynamic: "top-and-block-banner", seo: "/etc/product-listing-config/seobanners.csv" },
    endecaCanonical: "/electricals/dishwashers/_/N-ado",
    baseFacetId: "/electricals/dishwashers/_/N-ado",
};
