export default {
    productId: "4233088",
    bundleProducts: [],
    details: {
        returns:
            '<div class="par parsys">\n <div class="cms30r section">\n  <div class="free-html"> \n   <style>#cq-returns-info p a{padding:0;} #cq-returns-info h2{padding:18px 0 16px 0; border-bottom: 1px solid #bfbdb7; font-size: 18px; font-weight: bold;} #cq-returns-info p{padding:0 0 6px;}\n   </style>\n   <div id="cq-returns-info"> \n    <h2>Returns</h2> \n    <p>If you’ve changed your mind about keeping your purchase, please return it in its original condition with proof of purchase and we’ll exchange or refund it. Unless faulty, this should be within 35 days of receiving your order. By original condition, we’d expect this to mean that you’ve kept packaging and labels, and that the item is undamaged and unused.</p> \n    <p>You can return for free in the UK via John Lewis and Waitrose Shops, Royal Mail, Collect+ or MyHermes. If you need to arrange collection of large or heavy items, call us on <strong>03456 049 049</strong>. For international returns queries, call us on <strong>+44 1698 545 454</strong></p> \n    <p>You’ll find returns information on your delivery note. Exceptions apply to certain products - <a href="/customer-services/information-about-ordering-and-returning-products#refund">find out more about our refund policy</a></p>\n   </div>\n  </div>\n </div>\n</div>',
        returnsHeadline:
            '<div class="par parsys">\n <div class="cms30r section">\n  <div class="free-html"> \n   <style type="text/css">.free-html a.more-details {   font-weight:normal;}}.returns-info { float:left;}.returns-info h2 {float:left;padding-right:10px;}.returns-info-link { padding:4px 0 15px 0;}\n   </style>\n   <div class="returns-info">\n    <h2><a href="#tabinfo-returns" class="tab-link">Returns -</a></h2>\n    <div class="returns-info-link">\n     <a href="#tabinfo-returns" class="more-details ">See more details</a>\n    </div>\n   </div>\n  </div>\n </div>\n</div>',
        termsAndConditions: "",
        productInformation:
            "<p>Complete your kitchen with the John Lewis & Partners JLBIDW1419</p>",
        features: [
            {
                groupName: "",
                attributes: [
                    {
                        value: "Integrated",
                        values: [],
                        multivalued: false,
                        id: "attr60000440611",
                        name: "Type",
                        toolTip: "",
                        uom: "",
                    },
                    {
                        value: "YES",
                        values: [],
                        multivalued: false,
                        id: "attr60000440612",
                        name: "Rinse Aid Indicator",
                        toolTip: "",
                        uom: "",
                    },
                    {
                        value: "46dB",
                        values: [],
                        multivalued: false,
                        id: "attr60000440613",
                        name: "Noise Level",
                        toolTip:
                            "How noisy, in decibels, the machine is. The lower the dB, the quieter the appliance. A human voice in normal conversation is approximately 60dB, while an alarm clock might be 80dB",
                        uom: "",
                    },
                    {
                        value: "85kWh",
                        values: [],
                        multivalued: false,
                        id: "attr60000440660",
                        name: "Weighted Energy Consumption per 100 cycles for Eco cycle",
                        toolTip: "",
                        uom: "",
                    },
                ],
            },
        ],
        careGuide: [],
        featuredArticles: [
            {
                title: "Dishwashers Buying Guide",
                image: "//johnlewis.scene7.com/is/image/JohnLewis/electrical_med_icon?",
                linkUrl: "https://www.johnlewis.com/buying-guides/dishwashers-buying-guide",
                linkText: "Dishwashers Buying Guide",
                longDescription: "Wave farewell to the washing up with your new friend in the kitchen",
                pdfUrl: "",
            },
            {
                title: "Built-in Appliances Buying Guide",
                image: "//johnlewis.scene7.com/is/image/JohnLewis/electrical_med_icon?",
                linkUrl: "https://www.johnlewis.com/buying-guides/built-in-appliances-buying-guide",
                linkText: "Built-in Appliances Buying Guide",
                longDescription:
                    "Built-in (or integrated) washing machines, washer dryers and dishwashers offer a sleek and unobtrusive look",
                pdfUrl: "",
            },
        ],
        editorsNotes:
            "<p>When you're part of it, you put your heart into it.</p><p>At John Lewis & Partners, we're more than employees - we're owners. That's why we're all called Partners.</p><p>And that's why we all go above and beyond to offer quality products and outstanding service to the people that matter most - you, our customers.</p><p>Because for us, it's personal.</p>",
        buyingGuides: [
            {
                title: "Dishwashers Buying Guide",
                image: "//johnlewis.scene7.com/is/image/JohnLewis/electrical_med_icon?",
                linkUrl: "https://www.johnlewis.com/buying-guides/dishwashers-buying-guide",
                linkText: "Dishwashers Buying Guide",
                longDescription: "Wave farewell to the washing up with your new friend in the kitchen",
            },
            {
                title: "Built-in Appliances Buying Guide",
                image: "//johnlewis.scene7.com/is/image/JohnLewis/electrical_med_icon?",
                linkUrl: "https://www.johnlewis.com/buying-guides/built-in-appliances-buying-guide",
                linkText: "Built-in Appliances Buying Guide",
                longDescription:
                    "Built-in (or integrated) washing machines, washer dryers and dishwashers offer a sleek and unobtrusive look",
            },
        ],
        sizeGuides: [],
        weLikeItBecause: "",
    },
    deliveries: [
        {
            deliveryType: "UK",
            options: [
                {
                    id: "26",
                    price: "0.00",
                    currency: "GBP",
                    shortDescription:
                        "Delivery from 3 days, depending on postcode, charges apply to locations outside of UK mainland",
                    standardDescription:
                        "Delivery from 3 days, depending on postcode, charges apply to locations outside of UK mainland",
                    date: "",
                    dateMessage: "",
                    trialMessage: "",
                    isApprovedSupplier: false,
                    leadTime: 0,
                    cutOffTime: 1,
                    newShortDescription: "Standard Delivery",
                    newStandardDescription:
                        "Delivery to UK mainland locations from 3 working days of your order, delivered on the day of your choice, Monday to Saturday.||Choose your preferred delivery day in checkout. 2-hour and 4-hour slots are available for an additional cost.||Availability varies by postcode. <a href='https://www.johnlewis.com/customer-services/delivery-information/uk-delivery'>Charges apply to locations outside of UK mainland</a>.",
                    newPriority: 1,
                },
                {
                    id: "202",
                    price: "19.95",
                    currency: "GBP",
                    shortDescription: "Next day delivery to selected areas",
                    standardDescription: "Next day delivery to selected areas",
                    date: "",
                    dateMessage: "",
                    trialMessage: "",
                    isApprovedSupplier: false,
                    leadTime: 2,
                    cutOffTime: 20,
                    newShortDescription: "Next Day Delivery",
                    newStandardDescription:
                        "Order by 2pm for next day delivery, 11am - 9pm, Monday to Saturday. The evening before delivery day we'll let you know a 2-hour delivery window.||Availability varies by postcode. Not available to non-mainland locations, or when ordered with installation and disposal services.",
                    newPriority: 4,
                },
            ],
        },
    ],
    deliverySummary: [
        {
            deliveryType: "UK",
            title: "UK delivery",
            price: "0.00",
            currency: "GBP",
            summary: "Delivery from 3 days, depending on postcode, charges apply to locations outside of UK mainland",
            trialMessage: "",
            newTitle: "Standard Delivery",
            newSummary:
                "Delivery to UK mainland locations from 3 working days of your order, delivered on the day of your choice, Monday to Saturday.||Choose your preferred delivery day in checkout. 2-hour and 4-hour slots are available for an additional cost.||Availability varies by postcode. <a href='https://www.johnlewis.com/customer-services/delivery-information/uk-delivery'>Charges apply to locations outside of UK mainland</a>.",
            newPriority: 1,
            newOptionId: "26",
        },
    ],
    emailMeWhenAvailable: true,
    skus: [
        {
            id: "238096018",
            skuTitle: "John Lewis & Partners JLBIDW1419 Fully Integrated Dishwasher",
            shortSkuTitle: "",
            color: "",
            size: "",
            sizeHeadline: "",
            swatchUrl:
                "//johnlewis.scene7.com/is/image/JohnLewis/238096018?cropN=0.42105263157894735,0.42105263157894735,0.16842105263157894,0.16842105263157894&",
            availability: {
                stockLevel: 194,
                availabilityStatus: "INSTOCK",
                message: "Currently in stock online",
            },
            price: {
                was: "",
                then1: "",
                then2: "",
                now: "429.00",
                uom: "",
                currency: "GBP",
            },
            code: "88700203",
            leadTime: "",
            d2cDeliveryLeadTime: "",
            media: {
                images: {
                    altText: "Buy John Lewis & Partners JLBIDW1419 Fully Integrated Dishwasher Online at johnlewis.com",
                    urls: [
                        "//johnlewis.scene7.com/is/image/JohnLewis/238096018alt1?",
                        "//johnlewis.scene7.com/is/image/JohnLewis/238096018?",
                        "//johnlewis.scene7.com/is/image/JohnLewis/238096018alt2?",
                        "//johnlewis.scene7.com/is/image/JohnLewis/238096018alt3?",
                        "//johnlewis.scene7.com/is/image/JohnLewis/238096018alt4?",
                        "//johnlewis.scene7.com/is/image/JohnLewis/238096018alt10?",
                    ],
                },
                "360images": {
                    swfUrl: "//johnlewis.scene7.com/is/content/JohnLewis/360-degree-view",
                    urls: [],
                },
            },
            brandName: "John Lewis & Partners",
            unitPriceInfo: {},
            priceBand: "",
            dynamicAttributes: {
                crediteligibilitystatus: "Core",
                modelnamenumber: "JLBIDW1419",
            },
            ticketType: "T",
            mainframeProductId: "1kj1Nxe1",
        },
    ],
    title: "John Lewis & Partners JLBIDW1419 Fully Integrated Dishwasher",
    defaultSku: "238096018",
    storeOnly: false,
    type: "standard",
    ageRestriction: 0,
    seoURL: "/john-lewis-partners-jlbidw1419-fully-integrated-dishwasher/p4233088",
    isFBL: false,
    averageRating: 3.4,
    numberOfReviews: 28,
    price: {
        was: "",
        then1: "",
        then2: "",
        now: "429.00",
        uom: "",
        currency: "GBP",
    },
    code: "88700203",
    specialOffers: {
        priceMatched: "",
        offer: "",
        customPromotionalMessage: "",
        bundleHeadline: "",
        customSpecialOffer: {
            customSpecialOfferId: "60002500017",
            imageURL: "",
            linkText: "",
            linkURL: "",
            longDescription: "Save £60 (price includes saving)",
            promoImageName: "",
            siteDisplayName: "Save £60 (price includes saving)",
        },
    },
    displaySpecialOffer: "Save £60 (price includes saving)",
    setDetails: {},
    templateType: "media-epic-prodtemplate",
    priceBands: [],
    legs: [],
    swatchCategoryType: "",
    deliveryFulfilledBy: "greenVanFleet",
    additionalServices: {
        includedServices: ["3 year guarantee included"],
        optionalServices: [
            {
                id: "233599178",
                associatedProductId: "1465821",
                title: "5 years Protect Plus for your home appliance (includes guarantee period)",
                description:
                    "Our electrical products are guaranteed against breakdown for a minimum of 2 years at no extra cost. With Protect Plus, you'll get up to 5 years of protection against accidental damage alongside your guarantee. <a href='https://www.johnlewis.com/protectplus'>More about Protect Plus</a>",
                price: "80.00",
                currency: "GBP",
                orderOnSite: 1,
                type: "ADDED_WARRANTY",
                url: "/protectplus",
                customProperties: {
                    warrantyCustomGeneric:
                        "Exclusions apply. To make sure this policy meets your needs, please read the <a href='https://johnlewis.scene7.com/is/content/JohnLewis/IPID-Home-Appliancepdf'>Insurance Product Information Document</a>.",
                    warrantyCustomTooltip:
                        "Our electrical products are guaranteed against breakdown for a minimum of 2 years at no extra cost. With Protect Plus for your home appliance, you'll get 5 years of protection against breakdown and accidental damage alongside your guarantee. <a href='https://www.johnlewis.com/our-services/protect-plus'>More about Protect Plus</a>.",
                    warrantyCustomDescription:
                        "Would you like to protect your home appliance for 5 years against breakdown (includes guarantee period) and accidental damage with Protect Plus?",
                    warrantyCustomConfirm:
                        "You've chosen Protect Plus to protect your home appliance against breakdown (includes guarantee period) and accidental damage for 5 years.  Terms and conditions apply.  Please ensure you have read the <a href='https://johnlewis.scene7.com/is/content/JohnLewis/IPID-Home-Appliancepdf'>Insurance Product Information Document</a> and <a href='https://www.johnlewis.com/our-services/protect-plus'>Terms and Important Information</a> to ensure this insurance product meets your demands and needs.",
                },
            },
            {
                id: "DMS14",
                associatedProductId: "DMS14",
                title: "Dishwasher Recycling",
                description:
                    "<p>Our recycling service includes the taking away of your old appliance & packaging. The materials will be reused or recycled to create less waste & impact on the environment.</p>\n\n<p>Please drain/remove the contents of your old appliance and safely disconnect from the water/electricity supply.</p>\n\n<p>If you've booked a recycling service, please place your old appliance outside your home before our team's arrival. If you've booked an installation and recycling service, we'll take your old appliance away from the room.</p>",
                price: "20.00",
                currency: "GBP",
                orderOnSite: 2,
                type: "DBS",
                url: "",
                customProperties: {},
            },
            {
                id: "DMS3902",
                associatedProductId: "DMS3902",
                title: "Integrated Dishwasher Installation",
                description:
                    "<p><b>What this includes</b></p>\n<ul>\n<li>Connection of the appliance to an existing water connection point that is within 1 metre of installation location</li>\n<li>Connection of the appliance to an existing 3 pin 13 amp plug socket or hard-wired electricity point that is within 1 metre of installation location.</li>\n<li>Connection of the appliance to an existing waste outlet that is within 1 metre of the installation location</li>\n<li>Test wash to ensure that the appliance fills and drains correctly</li>\n<li>Refitting of the decorative door(s)</li>\n<li>Removal of all packaging</li></ul>",
                price: "90.00",
                currency: "GBP",
                orderOnSite: 3,
                type: "DBS",
                url: "",
                customProperties: {},
            },
        ],
    },
    media: {
        images: {
            altText: "Buy John Lewis & Partners JLBIDW1419 Fully Integrated Dishwasher Online at johnlewis.com",
            urls: [
                "//johnlewis.scene7.com/is/image/JohnLewis/238096018alt1?",
                "//johnlewis.scene7.com/is/image/JohnLewis/238096018?",
                "//johnlewis.scene7.com/is/image/JohnLewis/238096018alt2?",
                "//johnlewis.scene7.com/is/image/JohnLewis/238096018alt3?",
                "//johnlewis.scene7.com/is/image/JohnLewis/238096018alt4?",
                "//johnlewis.scene7.com/is/image/JohnLewis/238096018alt10?",
            ],
        },
        "360images": {
            swfUrl: "//johnlewis.scene7.com/is/content/JohnLewis/360-degree-view",
            urls: [],
        },
        videos: {},
    },
    setElements: [],
    headingTypes: [],
    moreFromRange: [],
    promotionalFeatures: [],
    setInformation: "",
    specialOfferBundles: [],
    fixedRelatedProducts: [],
    siblingSets: [],
    defaultCategory: {
        id: "6000047",
        name: "Dishwashers",
    },
    parentCategories: [
        {
            id: "8000017463",
            name: "Dishwasher Offers",
        },
        {
            id: "6000047",
            name: "Dishwashers",
        },
    ],
    releaseDateTimestamp: 0,
    crumbs: [
        {
            type: "CATALOGUE",
            displayName: "Electricals",
            item: "500001",
            clickable: "true",
        },
        {
            type: "CATALOGUE",
            displayName: "Dishwashers",
            item: "6000047",
            clickable: "true",
        },
    ],
    seoInformation: {
        title: "",
        description: "",
    },
    isInTopNkuCategory: true,
    brand: {
        name: "John Lewis & Partners",
        logo: "//johnlewis.scene7.com/is/image/JohnLewis/jl_partners_logo_2line_small_280818?",
    },
    swatchAvailable: false,
    madeToMeasureDetails: {
        type: "",
        styles: "",
    },
    isAsafShape: false,
    dynamicAttributes: {
        noiselevelrating: "C",
        weight: "37kg",
        timeremainingindicator: "YES",
        weightedenergyconsumptionper100cyclesforecocycle: "85kWh",
        integratedorfreestanding: "Integrated",
        smarttechnology: "Not Smart Technology Enabled",
        installationrequired: "NO",
        dishwashersize: "Full",
        waterconsumptionstandardcycle: "10.5L",
        saltlevelindicator: "YES",
        floodprotection: "YES",
        dryingsystem: "AutoOpen Drying",
        noiselevel: "46dB",
        digitaldisplay: "YES",
        delicatewash: "YES",
        quickwash: "YES",
        homearea: "Laundry & Cleaning",
        energyratingoverall: "D",
        timerdelay: "Yes - up to 24 hours",
        dryingperformance: "A",
        international: "No",
        homeappliancetype: "Dishwashers",
        countryoforigin: "Poland",
        cycledurationatratedcapacityfortheecocycle: "240 minutes",
        programsequenceindicator: "YES",
        washperformance: "A",
        adjustableracking: "YES",
        annualrunningcost: "£13.09",
        noofprograms: "8",
        guarantee: "3 year guarantee included",
        placesettings: "14",
        rinseaidindicator: "YES",
        slimdepth: "NO",
        weightedwaterconsumptionfortheecocycle: "10.5L",
    },
    excludeFromLiveChat: true,
    webPimProductType: "PRODUCT.Home & Garden.Domestic Appliances.Dishwashing Appliances.Dishwasher",
    nonPromoMessage: "",
    preorderable: false,
};
